### PR TITLE
add language option to manage non-english mstest.exe

### PR DESCRIPTION
**Pull request by plasmaboyer**
Support de mstest npm package 0.2.2

### CODE REVIEW

**Comment by legacybass** [comment]
Great option to add. Thanks!

**Comment by plasmaboyer** [comment]
Don't forget to push on npm : mstest is already in version 0.2.2
We all are waiting for your submit ;)

**Comment by legacybass** [comment]
Oh, thanks. I would have completely forgotten about that.

**Comment by legacybass** [comment]
Pushed to NPM. Again, thanks for the reminder.

**Pull request merged**
